
spring:
  datasource:
    password: Zayadbhaia1
    url: jdbc:postgresql://localhost:5432/waa_db
    username: postgres
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: false
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
server:
  port: 8080
